<?php
/**
 * Implements hook_process_html().
 */
function rdfa_xpath_process_html(&$variables) {
  $rdfa_mappings = module_invoke_all('rdfa_xpath_mappings');
  if (!empty($rdfa_mappings)) {
    // Create DOM XPath object to process.
    $dom = filter_dom_load($variables['page']);
    $dom_xpath = new DOMXPath($dom);

    foreach ($rdfa_mappings as $rdfa_mapping) {
      switch ($rdfa_mapping['type']) {
        case 'global':
          // Process global mappings.
          _rdfa_xpath_process_rdf_mappings($dom_xpath, $rdfa_mapping['mappings']);
          break;
        case 'node':
          $node = menu_get_object();
          if (isset($node->type) && $node->type == $rdfa_mapping['bundle']) {
            // Pass node context for token replacement.
            _rdfa_xpath_process_rdf_mappings($dom_xpath, $rdfa_mapping['mappings'], array('node' => $node));
          }
          break;
      }
    }

    // Replace the page HTML with processed RDFa.
    $variables['page'] = filter_dom_serialize($dom);
  }
}

/**
 * Process RDFa mappings.
 */
function _rdfa_xpath_process_rdf_mappings($dom_xpath, $mappings, $context = array()) {
  foreach ($mappings as $mapping) {
    if ($elements = $dom_xpath->query($mapping['xpath'])) {
      foreach ($elements as $element) {
        foreach ($mapping['attributes'] as $key => $value) {
          $element->setAttribute($key, token_replace($value, $context));
        }
      }
    }
  }
}
